//Script : cambioIdioma_js
//Creado el : 1-11-2019
//Creado por: ncgomez17
//---
//esta funcion nos permitirá cambiar de idioma en todos los textos que aparezcan en la arquitectura
function cambioIdioma(idioma){
	var strings_Idioma={//array que contendrá todos lo mensages a mostrar
	'SPANISH':{
		'Portal':'Portal de Gestión',
		'autor' :'Autor:Ncgomez17',
		'creacion':'Fecha Creación:28/10/2019',
		'usuario' : 'usuario',
		'data' : 'Hoy es ',
		'gusuarios': 'Gestión Usuarios',
		'gprofesores': 'Gestión Profesores',
		'gcentros': 'Gestión Centros',
		'gedificios':'Gestión Edificios',
		'gtitulaciones':'Gestión Titulaciones',
		'gespacios':'Gestión Espacios',
		'gprof_espacio':'Gestión Profesores-Espacios',
		'gprof_titulacion':'Gestión Profesores-Titulación',
		'nousuario':'Usuario no autenticado',
		'Login':'Login',
		'Password':'contraseña',
		'Nombre':'nombre',
		'Apellidos':'apellidos',
		'dni':'DNI',
		'Email':'email',
		'Foto':'foto',
		'Telefono':'telefono',
		'Fechanacimiento':'Fecha Nacimiento',
		'Sexo':'sexo',
		'Codtitulacion':'Código de Titulación',
		'Codcentro':'Código de Centro',
		'Nombretitulacion':'Nombre de la Titulacion',
		'Responsabletitulacion':'Responsable Titulacion',
		'Nombreprofesor':'Nombre Profesor',
		'Apellidosprofesor':'apellidosprofesor',
		'Areaprofesor':'areaprofesor',
		'Departamentoprofesor':'departamentoprofesor',
		'Añoacademico':'Año Academico',
		'Codespacio':'Código Espacio',
		'Codedificio':'Código Edificio',
		'Codcentro':'Código Centro',
		'Tipo':'Tipo',
		'Superficieespacio':'Superficie Espacio',
		'Numeroinventario':'Numero Inventario',
		'Nombreedificio':'Nombre Edificio',
		'Direccionedificio':'Dirección Edificio',
		'Campusedificio':'Campus Edificio',
		'Nombrecentro':'Nombre Centro',
		'Direccioncentro':'Direccion Centro',
		'Responsablecentro':'Responsable Centro',
		'añadir':'Añadir',
		'buscar':'Buscar',
		'borrar':'Borrar',
		'mostrardetalles':'Detalles',
		'editar':'Editar',
		'mostrartodos':'Mostrar todos',
		'registro':'Registro',
		'rogin':'Login',
		'introducion':'Introducción al funcionamiento de la página:',
		'gestion':'Esta web esta traducida a tres idiomas diferentes:español,inglés y gallego.',
		'bienvenido':'BIENVENIDO A LA ARQUITECTURA BASE DE IU ',
		'añadirentidades':'Añadir Entidades',
		'editarentidades':'Editar Entidades',
		'borrarentidades':'Borrar Entidades',
		'lupaentidades':'Buscar Entidades',
		'informacionentidades':'Información Entidades',
		'fin':'Esta web esta creada sobre una base de datos MYSQL y alojada en un servidor Apache',
		'Hombre':'hombre',
		'Mujer':'mujer',
		'Inserción fallida: el elemento ya existe':'Inserción fallida: el elemento ya existe',
		'Error de gestor de base de datos':'Error de gestor de base de datos',
		'Inserción realizada con éxito':'Inserción realizada con éxito',
		'El usuario ya existe':'El usuario ya existe',
		'La password para este usuario no es correcta':'La password para este usuario no es correcta',
		'El login no existe':'El login no existe',
		'Actualización realizada con éxito':'Actualización realizada con éxito',
		'Borrado realizado con éxito':'Borrado realizado con éxito',
		'Hay profesores que dependen de esta titulacion':'Hay profesores que dependen de esta titulacion',
		'Existen espacios o titulaciones que dependen de este profesor':'Existen espacios o titulaciones que dependen de este profesor',
		'No se puede borrar porque existe un profesor que depende de ese espacio':'No se puede borrar porque existe un profesor que depende de ese espacio',
		'No se puede borrar porque existen centros o espacios que dependen de este edificio':'No se puede borrar porque existen centros o espacios que dependen de este edificio',
		'No se puede borrar porque existen espacios y titulaciones que dependen de este centro':'No se puede borrar porque existen espacios y titulaciones que dependen de este centro',
		'fallos':'Errores producidos',
		'Despacho':'Despacho',
		'Laboratorio':'Laboratorio',
		'Pas':'PAS',
		"Fallo en el upload de la imagen":"Fallo en el upload de la imagen",
		'nombreatributo':'Nombre del atributo',
		'codigoincidencia':'Código de la incidencia',
		'mensajerror':'Mensaje de error'
	},
	'ENGLISH':{
		'Portal':'Management website',
		'autor' :'Author:Ncgomez17',
		'creacion' :'Creation Date:28/10/2019',
		'usuario' : 'user',
		'data' : 'Today is ',
		'gusuarios': 'Users Management',
		'gprofesores': 'Teachers Management',
		'gcentros': 'Centers Management',
		'gedificios':'Buildings Management',
		'gtitulaciones':'Degrees Management',
		'gespacios':'Spaces Management',
		'gprof_espacio':'Teachers-Spaces Management',
		'gprof_titulacion':'Teachers-Degrees Management',
		'nousuario':'User not Authenticated',
		'Login':'Login',
		'Password':'password',
		'Nombre':'name',
		'Apellidos':'surname',
		'dni':'DNI',
		'Email':'email',
		'Foto':'photo',
		'Telefono':'phone number',
		'Fechanacimiento':'Birth Date',
		'Sexo':'sex',
		'Codtitulacion':'Degree Code',
		'Codcentro':'Center Code',
		'Nombretitulacion':'Degree Name',
		'Responsabletitulacion':'Degree Manager',
		'Nombreprofesor':'Teacher Name',
		'Apellidosprofesor':'Teacher Surname',
		'Areaprofesor':'Teacher Area',
		'Departamentoprofesor':'Teacher Departament',
		'Añoacademico':'Academic Year',
		'Codespacio':'Space Code',
		'Codedificio':'Building Code',
		'Codcentro':'Center Code',
		'Tipo':'Type',
		'Superficieespacio':'Space Surface',
		'Numeroinventario':'Stock Number',
		'Nombreedificio':'Building Name',
		'Direccionedificio':'Building Address',
		'Campusedificio':'Campus Building',
		'Nombrecentro':'Center Name',
		'Direccioncentro':'Center Adress',
		'Responsablecentro':'Center Manager',
		'añadir':'Add',
		'buscar':'Search',
		'borrar':'Delete',
		'mostrardetalles':'Showcurrent',
		'editar':'Edit',
		'mostrartodos':'ShowAll',
		'registro':'Register',
		'rogin':'Login',
		'introducion':'Introduction to the operation of the page',
		'gestion':'This website is translated into three different languages: Spanish, English and Galician.',
		'bienvenido':'WELCOME TO IU BASIC ARCHITECTURE',
		'añadirentidades':'Add Entities',
		'editarentidades':'Edit Entities',
		'borrarentidades':'Delete Entities',
		'lupaentidades':'Search Entities',
		'informacionentidades':'Information Entities',
		'fin':'This web site is created on a MYSQL database and hosted on an Apache server',
		'Hombre':'man',
		'Mujer':'woman',
		'Inserción fallida: el elemento ya existe':'Insertion failed: item already exists',
		'Error de gestor de base de datos':'Database manager error',
		'Inserción realizada con éxito':'Successful insertion',
		'El usuario ya existe':'User already exists',
		'La password para este usuario no es correcta':'The password for this user is not correct',
		'El login no existe':'The login doesnt exists',
		'Actualización realizada con éxito':'Update successful',
		'Borrado realizado con éxito':'Deletion done successfully',
		'Hay profesores que dependen de esta titulacion':'There are teachers who depend on this degree',
		'Existen espacios o titulaciones que dependen de este profesor':'There are spaces or degrees that depend on this teacher',
		'No se puede borrar porque existe un profesor que depende de ese espacio':'You cant delete it because there is a teacher who depends on that space',
		'No se puede borrar porque existen centros o espacios que dependen de este edificio':'No se puede borrar porque existen centros o espacios que dependen de este edificio',
		'No se puede borrar porque existen espacios y titulaciones que dependen de este centro':'No se puede borrar porque existen espacios y titulaciones que dependen de este centro',
		'fallos':'Errors produced',
		'Despacho':'Office',
		'Laboratorio':'Laboratory',
		'Pas':'PAS',
		'Fallo en el upload de la imagen':'Image upload failed',
		'nombreatributo':'Attribute name',
		'codigoincidencia':'Incident Code',
		'mensajerror':'Error message'
		
	},
	'GALLAECIAN':{
		'Portal':'Portal de Xestión',
		'autor' :'Autor:Ncgomez17',
		'creacion' :'Data Creación:28/10/2019',
		'usuario' : 'usuario',
		'data' : 'Hoxe é ',
		'gusuarios': 'Xestión Usuarios',
		'gprofesores': 'Xestión Profesores',
		'gcentros': 'Xestión Centros',
		'gedificios':'Xestión Edificios',
		'gtitulaciones':'Xestión Titulacions',
		'gespacios':'Xestión Espazos',
		'gprof_espacio':'Xestión Profesores-Espazos',
		'gprof_titulacion':'Xestión Profesores-Titulacions',
		'nousuario':'Usuario non autenticado',
		'Login':'Login',
		'Password':'contrasinal',
		'Nombre':'nome',
		'Apellidos':'apelidos',
		'dni':'DNI',
		'Email':'email',
		'Foto':'foto',
		'Telefono':'telefono',
		'Fechanacimiento':'Fecha Nacemento',
		'Sexo':'sexo',
		'Codtitulacion':'Código da Titulación',
		'Codcentro':'Código do Centro',
		'Nombretitulacion':'Nome da Titulacion',
		'Responsabletitulacion':'Responsable Titulacion',
		'Nombreprofesor':'Nome Profesor',
		'Apellidosprofesor':'Apelidos profesor',
		'Areaprofesor':'Area profesor',
		'Departamentoprofesor':'Departamento profesor',
		'Añoacademico':'Ano Academico',
		'Codespacio':'Código Espazo',
		'Codedificio':'Código Edificio',
		'Codcentro':'Código Centro',
		'Tipo':'Tipo',
		'Superficieespacio':'Superficie Espazo',
		'Numeroinventario':'Numero Inventario',
		'Nombreedificio':'Nome Edificio',
		'Direccionedificio':'Dirección Edificio',
		'Campusedificio':'Campus Edificio',
		'Nombrecentro':'Nome Centro',
		'Direccioncentro':'Direccion Centro',
		'Responsablecentro':'Responsable Centro',
		'añadir':'Engadir',
		'buscar':'Buscar',
		'borrar':'Borrar',
		'mostrardetalles':'Detalles',
		'editar':'Editar',
		'mostrartodos':'Mostrar todos',
		'registro':'Registro',
		'rogin':'Login',
		'introducion':'Introducción ao funcionamiento da páxina:',
		'gestion':'Esta web esta traducida a tres idiomas diferentes:español,inglés e galego.',
		'bienvenido':'BENVIDO A ARQUITECTURA BASE DE IU ',
		'añadirentidades':'Añadir Entidades',
		'editarentidades':'Editar Entidades',
		'borrarentidades':'Borrar Entidades',
		'lupaentidades':'Buscar Entidades',
		'informacionentidades':'Información Entidades',
		'fin':'Esta web esta creada sobre unha base de datos MYSQL e aloxada nun servidor Apache',
		'Hombre':'home',
		'Mujer':'muller',
		'Inserción fallida: el elemento ya existe':'Inserción fallida: o elemento xa existe',
		'Error de gestor de base de datos':'Error do gestor da base de datos',
		'Inserción realizada con éxito':'Inserción realizada con éxito',
		'El usuario ya existe':'O usuario ya existe',
		'La password para este usuario no es correcta':'A password para este usuario non é correcta',
		'El login no existe':'O login non existe',
		'Actualización realizada con éxito':'Actualización realizada con éxito',
		'Borrado realizado con éxito':'Borrado realizado con éxito',
		'Hay profesores que dependen de esta titulacion':'Hai profesores que dependen desta titulacion',
		'Existen espacios o titulaciones que dependen de este profesor':'Existen espazos ou titulacions que dependen deste profesor',
		'No se puede borrar porque existe un profesor que depende de ese espacio':'Non se pode borrar porque existe un profesor que depende dese espazo',
		'No se puede borrar porque existen centros o espacios que dependen de este edificio':'Non se pode borrar porque existen centros ou espazos que dependen deste edificio',
		'No se puede borrar porque existen espacios y titulaciones que dependen de este centro':'Non se pode borrar porque existen espazos ou titulacions que dependen deste centro',
		'fallos':'Errores producidos',
		'Despacho':'Despacho',
		'Laboratorio':'Laboratorio',
		'Pas':'PAS',
		'Fallo en el upload de la imagen':'Fallo no upload da imaxen',
		'nombreatributo':'Nome do Atributo',
		'codigoincidencia':'Código da incidencia',
		'mensajerror':'Mensaxe de error'
		
	}
};

    
    
	for(var id in strings_Idioma[idioma]){//recorremos todo el array 
		if(document.getElementById(id)==null){//si el id es nullo no se hace nada
		}else{
		document.getElementById(id).innerHTML = strings_Idioma[idioma][id];//si el id se encuentra se manda el mensage que esta asociado al id
	}
	}
}

